Update sync-fork-with-upstream.yaml
update workflow

diff --git a/.github/workflows/sync-fork-with-upstream.yaml b/.github/workflows/sync-fork-with-upstream.yaml
--- a/.github/workflows/sync-fork-with-upstream.yaml
+++ b/.github/workflows/sync-fork-with-upstream.yaml
@@ -57,3 +57,15 @@ jobs:
       
     - name: Show value of 'has_new_commits'
       run: echo ${{ steps.sync.outputs.has_new_commits }}
+
+    #If there is no new commit then exit fail the action
+    - name: If no new commits, fail the action
+      if: steps.sync.outputs.has_new_commits == 'false'
+      run: exit 1
+
+  build-and-release:
+    needs: sync_latest_from_upstream
+    name: build-and-release
+    uses: gz-42/OpenDAoC-Core/.github/workflows/build-and-release.yaml@master
+    secrets:
+      PRIVATE_KEY_GITHUB: ${{ secrets.PRIVATE_KEY_GITHUB }}
